### ISSUE TITLE
Établir le programme détaillé

### ISSUE THREAD

**Issue by emchateau** [publicarchitectura/initiationXML#1]
Définir le programme détaillé de la formation

**Comment by emchateau** [comment]
Hello @lakonis,
Je viens de proposer une première esquisse de programme. Peux-tu me donner ton sentiment ?
https://github.com/publicarchitectura/initiationXML/blob/master/sources/00-programme.xml

**Comment by lakonis** [comment]
Ca me semble très bien de rentrer rapidement dans la pratique.
L'après-midi est presque entièrement consacrée à Xpath, je ne me rends pas compte selon le public si il vaut mieux développer les applications ou la technique.
